[package]
name = "led-statusboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daemonize = "0.5.0"
rpi-led-panel = { version = "0.3.0", features = ["drawing", "embedded-graphics"]}
tokio = { version = "1", features = ["full"] }
embedded-graphics = "0.7.1"
rocket = { version = "=0.5.0-rc.3", features = ["json"] }

[dependencies.rocket_dyn_templates]
version = "=0.1.0-rc.3"
features = ["tera"]