[package]
name = "led-statusboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["http_server"]
http_server = ["dep:rocket"]

[dependencies]
rpi-led-panel = { version = "0.3.0", features = ["drawing", "embedded-graphics"]}
tokio = { version = "1", features = ["full"] }
embedded-graphics = "0.7.1"
rocket = { version = "=0.5.0-rc.3", features = ["json"], optional = true }
serde = { version = "1.0.162", features = ["derive"] }
serde_yaml = "0.9.21"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
anyhow = "1.0.71"
bus = "2.4.0"

[dependencies.rocket_dyn_templates]
version = "=0.1.0-rc.3"
features = ["tera"]
