[workspace]
resolver = "2"
members = [
    "rustic_pixel_display/macros",
    "rustic_pixel_display/sdk",
    "examples/tracker_renders",
    "examples/train_renders",
    "examples/weather_renders"
]

[workspace.package]
version = "1.0.0"