name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
        rust:
          - stable
        features:
          - ""
          - "--features http_server"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          lfs: "false"

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Display Toolchain Information
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

#      - name: Lint
#        run: |
#          cargo fmt -- --check
#          cargo clippy -- -D warnings

      - name: Test
        run: |
          cargo check --no-default-features ${{ matrix.features }}
          cargo test --all --no-default-features ${{ matrix.features }}

      - name: Build
        run: |
          cargo build --release --no-default-features ${{ matrix.features }}
